<a href="https://colab.research.google.com/github/ranipuja235/puja_aiml/blob/main/06_01_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
yprint('Hello Pooja!')

Hello Pooja!


Using of parameters in print() statement.

In [ ]:
print('Hello' , end='\n\n')
print('Abit')

Hello

Abit


In [ ]:
a = 6
b = 5
c = 2023
print(a,b,c , sep='-')

6-5-2023


In [ ]:
a=100
print('a =',a)

a = 100


In [ ]:
nm = input('Enter Name')
print(nm)

Enter NamePooja
Pooja


In [ ]:
#Using of plus operator.
a = input('Enter a ')
b = input('Enter b ')
c = a+b
print('C value is = ' , c)


Enter a 22
Enter b 44
C value is =  2244


In [ ]:
#Using of plus operator.
a = int(input('Enter a '))
b = int(input('Enter b '))
c = a+b
print('C value is = ' , c)

Enter a 22
Enter b 66
C value is =  88


In [ ]:
#The type() function

a = 20
print(type(a))
b = 8.99
print(type(b))
c = False
print(type(c))
d = "abit"
print(type(d))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


In [ ]:
x=0b10100
y=100
z=0o215
u=0x12d
float_1=100.5
float_2=1.5e2
a=5+3.14j
print(x,y,z,u)
print(float_1,float_2)
print(a,a.imag,a.real)

20 100 141 301
100.5 150.0
(5+3.14j) 3.14 5.0


In [ ]:
a=2+5j
b=3+10j
c=a+b
print(c)

(5+15j)


In [ ]:
a=2
b=5
print(2**5)

32


In [ ]:
a=8
b=3
print(a/b)
print(a//b)

2.6666666666666665
2


In [ ]:
a=True
b=True
c=False
print(a and b)

print(a and c)

print(a or b)

print(not c)

True
False
True
True


In [ ]:
a=5
b=2
print(a<<b)

20


In [ ]:
a=5
b=2
print(a>>b)

1


In [ ]:
a=5
a+=5
print(a)
a-=5
print(a)

10
5


In [ ]:
a=5
a*=5
print(a)
a/=5
print(a)

25
5.0


In [ ]:
a=5
a%=5
print(a)
a//=5
print(a)

0
0


In [ ]:
a=5

print(a)
a>>=2
print(a)
a<<=5
print(a)

5
1
32


In [ ]:
x=5
y=5
print(x is y)
y=6
print(x is not y)

True
True


In [ ]:
x='HELLO'
print('A' in x)
print('A' not in x)

False
True


In [ ]:
a=int(input('enter a number'))
if a%2==0:
  print('Even No=',a)

enter a number6
Even No= 6


In [ ]:
a=int(input('enter a number'))
if a%2==0:
  print('Even No=',a)
else:
 print('odd No=',a)

enter a number5
odd No= 5


#using if-ELIF statement

In [ ]:
number=int(input("Enter the number?"))
if number==10:
  print("number is equal to 10")
elif number==50:
  print("number is equal to 50");
elif number==100:
  print("number is equal to 100");
else:
  print("number is not equal to 10,50 and 100");

Enter the number?51
number is not equal to 10,50 and 100


In [ ]:
x='pujarani'
for i in x:
  print(i)


p
u
j
a
r
a
n
i


In [ ]:
#to create table
list=[1,2,3,4,5,6,7,8,9,10]
n=5 
for i in list :
  c=n*i
  print(c)


5
10
15
20
25
30
35
40
45
50


In [ ]:
#to create table
list=[1,2,3,4,5,6,7,8,9,10]
n=int(input('enter your choice'))
for i in list :
  c=n*i
  print(c)

enter your choice3
3
6
9
12
15
18
21
24
27
30


In [ ]:
#to create table
list=[10,30,23,43,65,12]
sum=0
for i in list:
  sum=sum+i
print("the sum is:",sum)

the sum is: 183


In [ ]:
#using range() function in the loop
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(10):
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [ ]:
n=int(input("enter the number "))
for i in range(1,11):
  c=n*i
  print(n,"*",i,"=",c)

enter the number 10
10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


In [ ]:
n=int(input("enter the number"))
for i in range(2,n,2):
  print(i)

enter the number20
2
4
6
8
10
12
14
16
18


In [ ]:
n=int(input("enter the number="))
sum=0
for i in range(2,n,2):
  sum=sum+i
print("thr sum is",sum) 


enter the number=10
thr sum is 20


In [ ]:
#using len() function
list=['Peter','Joseph','Ricky','Devansh']
for i in range(len(list)):
  print("HELLO",list[i])


HELLO Peter
HELLO Joseph
HELLO Ricky
HELLO Devansh


In [ ]:
#nested for loop
for i in range(5):
  for j in range(5):
    print(i,end='')
  print('')


00000
11111
22222
33333
44444


In [ ]:
#nested for loop
for i in range(1,6):
  for j in range(5):
    print(i,end='')
  print('')


11111
22222
33333
44444
55555


In [ ]:
#user input for number of rows
rows=int(input("enter the rows:"))
#outer loop will print number of rows
for i in range(0,rows+1):
#inner loop will print number of Astrick
 for j in range(i):
  print("*",end=" ")
 print()

enter the rows:5

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
#program to number pyramid.
rows=int(input("enter the rows"))
for i in range(0,rows+1):
  for j in range(i):
    print(i,end=" ")
  print( )

enter the rows5

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
#using while loop
s=0
i=1
while i<=10:
  s=s+i
  i=i+1
print('sum from 1 to 10=',s)

sum from 1 to 10= 55


In [ ]:
s=int(input("enter the number= "))
rev=0
while s>0:
  d=int(s%10)
  rev=(rev*10+d)
  s=int(s/10)
print('reverse =',rev)

        

enter the number= 123
reverse = 321


In [ ]:
#break statement
i=1
while i<=10:
  print(i)
  if i==5:
    break
  i=i+1

1
2
3
4
5


In [ ]:
#contiue statement
for var in "ABIT":
  if var=="B":
    continue
  print(var)

A
I
T


In [ ]:
#break statement
for i in range(10):
  print(i)
  if i==2:
    break

0
1
2


In [ ]:
#write a program to print 1 to 10 remove 5
for i in range(10):
  if i==5:
    continue
  print(i)

0
1
2
3
4
6
7
8
9


In [ ]:
#pass statement
puja=['a','b','c','d']
for i in puja:
  if(i=='a'):
    pass
  else:
    print(i)

b
c
d


In [ ]:
#write a python program to print n even numbers and pass the value after 10 upto n.
n=int(input("enter the number"))
for i in range(2,n+1,2):
  if(i<=10):
    pass
  else:
    print(i)


enter the number20
12
14
16
18
20


In [ ]:
#using python function
def puja():
  print('HELLO PYTHON')
puja()
  


HELLO PYTHON


In [ ]:
def sum(a,b):
  print('a+b =',(a+b))
sum(22,33)

a+b = 55


In [ ]:
def sum(a,b):
  print('a+b =',(a+b))
x=int(input("enter x= "))
y=int(input("enter y= 56"))
sum(x,y)

enter x= 45
enter y= 56
a+b = 101


In [ ]:
#write a python program using function and take the input from the keyboard of the number to reverse it and count number of odd and even
num=(1,2,3,4,5,6,7,8,9)
reversed_num=0
while num !=0:
  digit=num % 10
  reversed_num=reversed_num *10 + digit
  num //=10
print("reversed number :  " + str(reversed_num))
for x in num:
  if 


In [ ]:
#write a python program the base class contains the addition of two numbers and the derived class contains multiplication of same two number.
class a():
  def sum(self,a,b):
    return a+b
class b(a):
  def mul(self,a,b):
    return a*b
d=b()
a=int(input("Enter 1st number.."))
b=int(input("Enter 2nd number.."))
print(d.sum(a,b))
print(d.mul(a,b))




Enter 1st number..23
Enter 2nd number..34
57
782


In [ ]:
class base:
  def add(self,a,b):
    return a+b
class derived (base):
  def mul(self,a,b):
    return a*b
m=int(input('a='))
n=int(input('b='))
obj=derived()
print(obj.add(m,n))
print(obj.mul(m,n))


a=2
b=3
5
6


In [ ]:
#write a python program using multilable inheritance to design calculator whose contains four derived of derived classes but only one child or derived classes.
class A():
 def sum(self,a,b):
  return a+b
class B(A):
 def sub(self,a,b):
  return a-b
class C(B):
 def mul(self,a,b):
  return a*b
class D(C):
 def div(self,a,b):
  return a/b
class E(D):
 def rem(self,a,b):
  return a%b
d=E()
a=int(input('INPUT a='))
b=int(input('INPUT b='))
print(d.sum(a,b))
print(d.sub(a,b))
print(d.mul(a,b))
print(d.div(a,b))
print(d.rem(a,b))

INPUT a=5
INPUT b=6
11
-1
30
0.8333333333333334
5


In [ ]:
#write a python program to input employee information imp id,name,basic salary,hra=15%,ta=5% and medical allounce=5% if basic salary is 5000 and if 10% more than 10000 using single inheritance .the base class contains all the emploeey information but the derived class contains the net salalry of the emp with all information..
print("SALARY PROGRAM")
name= str(input("Enter name of employee:"))
basic=float(input("Enter Basic Salary :"))
da=float(basic*0.25)
hra=float(basic*0.15)
pf=float((basic+da)*0.12)
ta=float(basic*0.075)
netpay=float(basic+da+hra+ta)
grosspay=float(netpay-pf)

print("\n\n")
print("SALARY DETAILED BREAK UP ")
print("===========================")
print(" NAME OF EMPLOYEE : ",name)
print(" BASIC SALARY : ",basic)
print(" DEARNESS ALLOW. : ",da)
print(" HOUSE RENT ALLOW.: ",hra)
print(" TRAVEL ALLOW. : ",ta)
print("======================")
print(" NET SALARY PAY : ",netpay)
print(" PROVIDENT FUND : ",pf)
print("========================")
print(" GROSS PAYMENT : ",grosspay)
print("============================")



SALARY PROGRAM
Enter name of employee:puja
Enter Basic Salary :1000



SALARY DETAILED BREAK UP 
 NAME OF EMPLOYEE :  puja
 BASIC SALARY :  1000.0
 DEARNESS ALLOW. :  250.0
 HOUSE RENT ALLOW.:  150.0
 TRAVEL ALLOW. :  75.0
 NET SALARY PAY :  1475.0
 PROVIDENT FUND :  150.0
 GROSS PAYMENT :  1325.0


In [ ]:
import numpy
list=[10,20,30,40,50]
arr=numpy.array(list)
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print(arr)

[10 20 30 40 50]


In [ ]:
#to size,datatype,dimension and shape of one dimansion array
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print('size:',arr.size)
print('datatype:',arr.dtype)
print('dimension:',arr.ndim)
print('shape:',arr.shape)


size: 5
datatype: int64
dimension: 1
shape: (5,)


In [ ]:
#two dimension array
import numpy as np
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as np
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1])

[40 50 60]


In [ ]:
import numpy as np
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1][1])

50


In [ ]:
import numpy as np
three_dimensional_list=[[[1,2,3],[4,5,6],[7,8,9]]]
three_dimensional_arr=np.array(three_dimensional_list)
arr=np.array(list)
print("3D array is:",three_dimensional_arr)

3D array is: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
#conversion of 1D to 6D
import numpy as np
ndArray=np.array([1,2,3,4],ndmin=6)
print(ndArray)
print('dimensions of array:',ndArray.ndim)

[[[[[[1 2 3 4]]]]]]
dimensions of array: 6


In [ ]:
import numpy as np
list=[10,20,30,40,50,60]
att=np.array(list)
print('ELEMENT')
for ele in arr:
  print(ele)

ELEMENT
10
20
30
40
50


In [1]:
print("%10.3e"%(356.08977))

 3.561e+02


In [5]:
import numpy
n=int(input('enter size:'))
arr=numpy.ndarray(shape=(n),dtype=int)
print('enter %d element:' %n)
for i in range(n):
  arr[i]=int(input())
  print('array elements:',arr)

enter size:2
enter 2 element:
11
array elements: [11  0]
22
array elements: [11 22]


In [21]:
#add two number
import numpy
n = int (input('Enter Size:'))
arr = numpy.ndarray(shape=(n),dtype=int)
print('Enter %d element :'%n)
sum=0
for i in range(n):
  arr[i]=int(input())
  sum=sum+arr[i]
  print('array elements:',arr)
print(sum)

Enter Size:2
Enter 2 element :
11
array elements: [11 22]
22
array elements: [11 22]
33


In [11]:
#separate odd even
import numpy
n = int (input('Enter Size:'))
arr = numpy.ndarray(shape=(n),dtype=int)
print('Enter %d element :'%n)
def oddcount(a,o):
  if a%2!=0:
    o+=1
  return o
def evencount(a,e):
  if a%2==0:
    e+=1
  return e
o=0
e=0
for i in range(n):
  arr[i]=int(input())
  o=oddcount(arr[i],o)
  e=evencount(arr[i],e)
print('Array Elements :', arr)
print(o)
print(e)


Enter Size:2
Enter 2 element :
11
22
Array Elements : [11 22]
1
1


In [10]:
import numpy as np
list=[[10,20,30],[40,50,60],[70,80,90]]
arr=np.array(list)
print(arr)
# No Row and Column Size.
print('Slicing...... .....')
res=arr[:,:]
print(res)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing...... .....
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
import numpy as np
list=[[10,20,30],[40,50,60],[70,80,90]]
arr=np.array(list)
print(arr)
# No Row and Column Size.
print('Slicing...... .....')
s1=arr[:,:]
print(s1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing...... .....
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [29]:
import numpy as np
list=[[10,20,30],[40,50,60],[70,80,90]]
arr=np.array(list)
print(arr)
# No Row and Column Size.
print('Slicing...... .....')
s2=arr[1:3,1:3]
print(s2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing...... .....
[[50 60]
 [80 90]]


In [22]:
import numpy as np
list=[[10,20,30],[40,50,60],[70,80,90]]
arr=np.array(list)
print(arr)
# No Row and Column Size.
print('Slicing...... .....')
s2=arr[1:2,0:3]
print(s2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing...... .....
[[40 50 60]]


In [28]:
str='abit is an engineering college'
print(str[0:27:5])

ai nnl


In [35]:
str='abit is an engineering college'
print(str[0:27:5])
str1=slice(0,27,3)
str2=str[str1] 
print(str2)

ai nnl
atsnnnrgo


In [36]:
import pandas as pd 
import numpy as np 
info = np.array(['P','a','n','d','a','s']) 
a = pd.Series(info) 
print(a)

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


In [39]:
import pandas as pd 
info = ['rollno','age','name','hight','weight']
a = pd.Series(info) 
print(a)
df=pd.DataFrame(info)
print(df)
print("........................")
df

0    rollno
1       age
2      name
3     hight
4    weight
dtype: object
        0
0  rollno
1     age
2    name
3   hight
4  weight
........................


0
0  rollno
1     age
2    name
3   hight
4  weight